name: Deploy to Azure

on: [workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          client-id: 95b51dc8-05cf-4bb0-aab9-75689e54460c
          tenant-id: 3d4d17ea-1ae4-4705-947e-51369c5a5f79
          subscription-id: 6f7494fe-933c-456b-866d-8d626699fbae
      - name: Setup Pulumi CLI
        uses: pulumi/setup-pulumi@v2.0.0
      - name: Pulumi Preview
        uses: pulumi/actions@v4.0.0
        with:
          command: preview
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
