name: Deploy to Azure

on: [workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Pulumi CLI
        uses: pulumi/setup-pulumi@v2.0.0
      - name: Pulumi Up
        uses: pulumi/actions@v4.0.0
        with:
          command: up
          stack-name: dev
