name: Deploy to Azure

on:   
  workflow_dispatch:
    inputs:
      stack-name:
        description: 'Stack to deploy'
        required: true
        default: 'dev'
        type: string
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Pulumi CLI
        uses: pulumi/setup-pulumi@v2.0.0
      - name: Pulumi up
        uses: pulumi/actions@v4.0.0
        with:
          command: up
          stack-name: ${{ github.event.inputs.stack-name }}
      - name: Pulumi destroy
        uses: pulumi/actions@v4.0.0
        with:
          command: destroy
          stack-name: ${{ github.event.inputs.stack-name }}
